/**:
  ros__parameters:
    camera_name: "camera"
    unite_imu_method: "2"
    log_level: "info"
    output: "screen"

    rgb_camera:
      profile: '640x480x15'
    color_info_qos: "SENSOR_DATA"
    color_qos: "SENSOR_DATA"
    enable_color: true

    depth_module:
      profile: '640x480x60'
      emitter_enabled: 1
      emitter_on_off: true
      exposure:
        - 7500
        - 1
      gain:
        - 16
        - 16
    depth_qos: "SENSOR_DATA"
    depth_info_qos: "SENSOR_DATA"
    enable_depth: true

    infra1_module:
      profile: "640x480x30"
    infra2_module:
      profile: "640x480x30"
    enable_infra1: true
    enable_infra2: true
    infra_rgb: false
    infra_qos: "SENSOR_DATA"

    pointcloud:
      enable: false
      stream_filter: 2
      stream_index_filter: 0
    pointcloud_texture_index: 0
    pointcloud_texture_stream: RS2_STREAM_ANY

    tracking_module:
      profile: "0,0,0"
    enable_fisheye1: true
    enable_fisheye2: true
    enable_confidence: true
    gyro_fps: 200
    accel_fps: 200
    enable_gyro: true
    enable_accel: true
    enable_pose: true
    pose_fps: 200
    enable_sync: false
    align_depth:
      enable: false
    colorizer:
      enable: false
    clip_distance: -2.0
    linear_accel_cov: 0.01
    initial_reset: false
    allow_no_texture_points: false
    ordered_pc: false
    tf_publish_rate: 0.0
    diagnostics_period: 0.0
    decimation_filter:
      enable: false
    wait_for_device_timeout: -1.0
    reconnect_timeout: 6.0